jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "zach"
          password: "adm1npassw0rd"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: "CONFLUENT_CLOUD_API_KEY"
            secret: "${CONFLUENT_CLOUD_API_KEY}"
        - string:
            scope: GLOBAL
            id: "CONFLUENT_CLOUD_API_SECRET"
            secret: "${CONFLUENT_CLOUD_API_SECRET}"

jobs: 
  - file: /var/jenkins_home/groovy_jobs/tf-jobs.groovy
  - file: /var/jenkins_home/groovy_jobs/app-jobs.groovy
  # - file: /var/jenkins_home/groovy_jobs/branch-main.groovy
  # - file: /var/jenkins_home/groovy_jobs/branch-rel-2.0.0.groovy
  # - file: /var/jenkins_home/groovy_jobs/branch-rel-1.0.0.groovy

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - name: "jdk11"
  maven:
    installations:
    - name: "maven3.9.4"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  terraform:
    installations:
    - name: "terraform"
      properties:
      - installSource:
          installers:
          - terraformInstaller:
              id: "30816-linux-amd64"