jenkins:
  systemMessage: "Jenkins configured automatically by JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "zach"
          password: "adm1npassw0rd"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  views:
  - all:
      name: "all"
  - list:
      columns: ["status", "weather", "jobName", "lastSuccess", "lastFailure", "lastDuration", "buildButton"]
      includeRegex: "tf-infra-.*"
      name: "tf-infra-main"
  - list:
      columns: ["status", "weather", "jobName", "lastSuccess", "lastFailure", "lastDuration", "buildButton"]
      includeRegex: "^.*main.*"
      name: "release-main"
  - list:
      columns: ["status", "weather", "jobName", "lastSuccess", "lastFailure", "lastDuration", "buildButton"]
      includeRegex: "^.*rel-1.0.0.*"
      name: "release-1.0.0"
  - list:
      columns: ["status", "weather", "jobName", "lastSuccess", "lastFailure", "lastDuration", "buildButton"]
      includeRegex: "^.*rel-2.0.0.*"
      name: "release-2.0.0"

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: "confluent-cloud-creds"
            username: "${CONFLUENT_CLOUD_API_KEY}"
            password: "${CONFLUENT_CLOUD_API_SECRET}"
            description: "Confluent Cloud 'Cloud API Key & Secret' for Terraform/APIs"

jobs: 
  - file: /var/jenkins_home/groovy_jobs/tf-jobs.groovy
  - file: /var/jenkins_home/groovy_jobs/app-jobs.groovy

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - name: "jdk11"
  maven:
    installations:
    - name: "maven3.9.4"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  terraform:
    installations:
    - name: "terraform"
      properties:
      - installSource:
          installers:
          - terraformInstaller:
              id: "30816-linux-amd64"