/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.zacharydhamilton.events.vehicles;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Truck extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6025471469143158570L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Truck\",\"namespace\":\"com.github.zacharydhamilton.events.vehicles\",\"fields\":[{\"name\":\"wheels\",\"type\":\"int\",\"doc\":\"The number of wheels this vehicle has\"},{\"name\":\"make\",\"type\":\"string\",\"doc\":\"The make of the vehicle\"},{\"name\":\"model\",\"type\":\"string\",\"doc\":\"The model of the vehicle\"},{\"name\":\"trailer\",\"type\":\"boolean\",\"doc\":\"Whether or not this vehicle has a trailer\"},{\"name\":\"flatbed\",\"type\":\"boolean\",\"doc\":\"Whether or not this vehicle has a flatbed\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Truck> ENCODER =
      new BinaryMessageEncoder<Truck>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Truck> DECODER =
      new BinaryMessageDecoder<Truck>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Truck> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Truck> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Truck> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Truck>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Truck to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Truck from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Truck instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Truck fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The number of wheels this vehicle has */
  private int wheels;
  /** The make of the vehicle */
  private java.lang.CharSequence make;
  /** The model of the vehicle */
  private java.lang.CharSequence model;
  /** Whether or not this vehicle has a trailer */
  private boolean trailer;
  /** Whether or not this vehicle has a flatbed */
  private boolean flatbed;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Truck() {}

  /**
   * All-args constructor.
   * @param wheels The number of wheels this vehicle has
   * @param make The make of the vehicle
   * @param model The model of the vehicle
   * @param trailer Whether or not this vehicle has a trailer
   * @param flatbed Whether or not this vehicle has a flatbed
   */
  public Truck(java.lang.Integer wheels, java.lang.CharSequence make, java.lang.CharSequence model, java.lang.Boolean trailer, java.lang.Boolean flatbed) {
    this.wheels = wheels;
    this.make = make;
    this.model = model;
    this.trailer = trailer;
    this.flatbed = flatbed;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return wheels;
    case 1: return make;
    case 2: return model;
    case 3: return trailer;
    case 4: return flatbed;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: wheels = (java.lang.Integer)value$; break;
    case 1: make = (java.lang.CharSequence)value$; break;
    case 2: model = (java.lang.CharSequence)value$; break;
    case 3: trailer = (java.lang.Boolean)value$; break;
    case 4: flatbed = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'wheels' field.
   * @return The number of wheels this vehicle has
   */
  public int getWheels() {
    return wheels;
  }


  /**
   * Sets the value of the 'wheels' field.
   * The number of wheels this vehicle has
   * @param value the value to set.
   */
  public void setWheels(int value) {
    this.wheels = value;
  }

  /**
   * Gets the value of the 'make' field.
   * @return The make of the vehicle
   */
  public java.lang.CharSequence getMake() {
    return make;
  }


  /**
   * Sets the value of the 'make' field.
   * The make of the vehicle
   * @param value the value to set.
   */
  public void setMake(java.lang.CharSequence value) {
    this.make = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The model of the vehicle
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * The model of the vehicle
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'trailer' field.
   * @return Whether or not this vehicle has a trailer
   */
  public boolean getTrailer() {
    return trailer;
  }


  /**
   * Sets the value of the 'trailer' field.
   * Whether or not this vehicle has a trailer
   * @param value the value to set.
   */
  public void setTrailer(boolean value) {
    this.trailer = value;
  }

  /**
   * Gets the value of the 'flatbed' field.
   * @return Whether or not this vehicle has a flatbed
   */
  public boolean getFlatbed() {
    return flatbed;
  }


  /**
   * Sets the value of the 'flatbed' field.
   * Whether or not this vehicle has a flatbed
   * @param value the value to set.
   */
  public void setFlatbed(boolean value) {
    this.flatbed = value;
  }

  /**
   * Creates a new Truck RecordBuilder.
   * @return A new Truck RecordBuilder
   */
  public static com.github.zacharydhamilton.events.vehicles.Truck.Builder newBuilder() {
    return new com.github.zacharydhamilton.events.vehicles.Truck.Builder();
  }

  /**
   * Creates a new Truck RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Truck RecordBuilder
   */
  public static com.github.zacharydhamilton.events.vehicles.Truck.Builder newBuilder(com.github.zacharydhamilton.events.vehicles.Truck.Builder other) {
    if (other == null) {
      return new com.github.zacharydhamilton.events.vehicles.Truck.Builder();
    } else {
      return new com.github.zacharydhamilton.events.vehicles.Truck.Builder(other);
    }
  }

  /**
   * Creates a new Truck RecordBuilder by copying an existing Truck instance.
   * @param other The existing instance to copy.
   * @return A new Truck RecordBuilder
   */
  public static com.github.zacharydhamilton.events.vehicles.Truck.Builder newBuilder(com.github.zacharydhamilton.events.vehicles.Truck other) {
    if (other == null) {
      return new com.github.zacharydhamilton.events.vehicles.Truck.Builder();
    } else {
      return new com.github.zacharydhamilton.events.vehicles.Truck.Builder(other);
    }
  }

  /**
   * RecordBuilder for Truck instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Truck>
    implements org.apache.avro.data.RecordBuilder<Truck> {

    /** The number of wheels this vehicle has */
    private int wheels;
    /** The make of the vehicle */
    private java.lang.CharSequence make;
    /** The model of the vehicle */
    private java.lang.CharSequence model;
    /** Whether or not this vehicle has a trailer */
    private boolean trailer;
    /** Whether or not this vehicle has a flatbed */
    private boolean flatbed;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.zacharydhamilton.events.vehicles.Truck.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.wheels)) {
        this.wheels = data().deepCopy(fields()[0].schema(), other.wheels);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.make)) {
        this.make = data().deepCopy(fields()[1].schema(), other.make);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.model)) {
        this.model = data().deepCopy(fields()[2].schema(), other.model);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.trailer)) {
        this.trailer = data().deepCopy(fields()[3].schema(), other.trailer);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.flatbed)) {
        this.flatbed = data().deepCopy(fields()[4].schema(), other.flatbed);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Truck instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.zacharydhamilton.events.vehicles.Truck other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.wheels)) {
        this.wheels = data().deepCopy(fields()[0].schema(), other.wheels);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.make)) {
        this.make = data().deepCopy(fields()[1].schema(), other.make);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.model)) {
        this.model = data().deepCopy(fields()[2].schema(), other.model);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.trailer)) {
        this.trailer = data().deepCopy(fields()[3].schema(), other.trailer);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.flatbed)) {
        this.flatbed = data().deepCopy(fields()[4].schema(), other.flatbed);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'wheels' field.
      * The number of wheels this vehicle has
      * @return The value.
      */
    public int getWheels() {
      return wheels;
    }


    /**
      * Sets the value of the 'wheels' field.
      * The number of wheels this vehicle has
      * @param value The value of 'wheels'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder setWheels(int value) {
      validate(fields()[0], value);
      this.wheels = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'wheels' field has been set.
      * The number of wheels this vehicle has
      * @return True if the 'wheels' field has been set, false otherwise.
      */
    public boolean hasWheels() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'wheels' field.
      * The number of wheels this vehicle has
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder clearWheels() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'make' field.
      * The make of the vehicle
      * @return The value.
      */
    public java.lang.CharSequence getMake() {
      return make;
    }


    /**
      * Sets the value of the 'make' field.
      * The make of the vehicle
      * @param value The value of 'make'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder setMake(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.make = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'make' field has been set.
      * The make of the vehicle
      * @return True if the 'make' field has been set, false otherwise.
      */
    public boolean hasMake() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'make' field.
      * The make of the vehicle
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder clearMake() {
      make = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * The model of the vehicle
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * The model of the vehicle
      * @param value The value of 'model'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.model = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * The model of the vehicle
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'model' field.
      * The model of the vehicle
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder clearModel() {
      model = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'trailer' field.
      * Whether or not this vehicle has a trailer
      * @return The value.
      */
    public boolean getTrailer() {
      return trailer;
    }


    /**
      * Sets the value of the 'trailer' field.
      * Whether or not this vehicle has a trailer
      * @param value The value of 'trailer'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder setTrailer(boolean value) {
      validate(fields()[3], value);
      this.trailer = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'trailer' field has been set.
      * Whether or not this vehicle has a trailer
      * @return True if the 'trailer' field has been set, false otherwise.
      */
    public boolean hasTrailer() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'trailer' field.
      * Whether or not this vehicle has a trailer
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder clearTrailer() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'flatbed' field.
      * Whether or not this vehicle has a flatbed
      * @return The value.
      */
    public boolean getFlatbed() {
      return flatbed;
    }


    /**
      * Sets the value of the 'flatbed' field.
      * Whether or not this vehicle has a flatbed
      * @param value The value of 'flatbed'.
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder setFlatbed(boolean value) {
      validate(fields()[4], value);
      this.flatbed = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'flatbed' field has been set.
      * Whether or not this vehicle has a flatbed
      * @return True if the 'flatbed' field has been set, false otherwise.
      */
    public boolean hasFlatbed() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'flatbed' field.
      * Whether or not this vehicle has a flatbed
      * @return This builder.
      */
    public com.github.zacharydhamilton.events.vehicles.Truck.Builder clearFlatbed() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Truck build() {
      try {
        Truck record = new Truck();
        record.wheels = fieldSetFlags()[0] ? this.wheels : (java.lang.Integer) defaultValue(fields()[0]);
        record.make = fieldSetFlags()[1] ? this.make : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.model = fieldSetFlags()[2] ? this.model : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.trailer = fieldSetFlags()[3] ? this.trailer : (java.lang.Boolean) defaultValue(fields()[3]);
        record.flatbed = fieldSetFlags()[4] ? this.flatbed : (java.lang.Boolean) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Truck>
    WRITER$ = (org.apache.avro.io.DatumWriter<Truck>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Truck>
    READER$ = (org.apache.avro.io.DatumReader<Truck>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.wheels);

    out.writeString(this.make);

    out.writeString(this.model);

    out.writeBoolean(this.trailer);

    out.writeBoolean(this.flatbed);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.wheels = in.readInt();

      this.make = in.readString(this.make instanceof Utf8 ? (Utf8)this.make : null);

      this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);

      this.trailer = in.readBoolean();

      this.flatbed = in.readBoolean();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.wheels = in.readInt();
          break;

        case 1:
          this.make = in.readString(this.make instanceof Utf8 ? (Utf8)this.make : null);
          break;

        case 2:
          this.model = in.readString(this.model instanceof Utf8 ? (Utf8)this.model : null);
          break;

        case 3:
          this.trailer = in.readBoolean();
          break;

        case 4:
          this.flatbed = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










